---
- hosts: all
  become: yes
  gather_facts: no

  vars_files:
    - env.yml

  pre_tasks:
    - name: "Update the APT cache"
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - role: vim
      tags: vim

    - role: ha
      tags: ha

    - role: cloudflared
      tags: cf

    # Not used anymore. Climate control moved to another system.
    #- role: 1wire
    #  tags: 1wire
